### ISSUE TITLE
Labelify logo offer

### ISSUE THREAD

**Issue by reallinfo** [itgalaxy/labelify#1]
Hello, I am a graphic designer. I contribute to open source softwares by designing logos. Do you want me to design a logo for labelify? Do you have a logo idea?  I will wait for feedback. Have a nice day!

**Comment by alexander-akait** [comment]
@reallinfo Awesome! Let's do it :+1:

**Comment by reallinfo** [comment]
I designed a logo. What do you think about? Also, I can apply the colors you like. I used the automate icon and label icon.

![labelify](https://user-images.githubusercontent.com/36298335/40724762-8130936a-642a-11e8-9942-97823242d223.jpg)

**Comment by alexander-akait** [comment]
@reallinfo Thanks, right bottom looks awesome! Maybe try to use yellow and/or red color. A lot of labels in guthub it is `bug` and they always red :smile:

**Comment by reallinfo** [comment]
Sure! which one do you prefer?

![l2](https://user-images.githubusercontent.com/36298335/40727305-48570000-6430-11e8-9a2f-2c318ac3d12b.jpg)

**Comment by alexander-akait** [comment]
@reallinfo 1 red :+1:

**Comment by reallinfo** [comment]
okay, please check the pullrequest https://github.com/itgalaxy/labelify/pull/2

**Comment by alexander-akait** [comment]
Thanks!
